let car = 'bmw';
console.log("Is car == 'bmw'? I predict True.");
console.log(car == 'bmw');
let car1 = 'bmw';
console.log("Is car == 'bmw'? I predict True.");
console.log(car1 == 'audi');
let car2 = 'mercedes';
console.log("Is car == 'mercedes'? I predict True.");
console.log(car2 == 'mercedes');
let car3 = 'bmw';
console.log("Is car == 'bmw'? I predict True.");
console.log(car3 == 'mercedes');
let fees = 'paid';
console.log("Is car == 'paid'? I predict True.");
console.log(fees == 'paid');
let fees1 = 'paid';
console.log("Is car == 'paid'? I predict True.");
console.log(fees1 == 'notpaid');
let fees2 = 'unpaid';
console.log("Is car == 'unpaid'? I predict True.");
console.log(fees2 == 'unpaid');
let fees3 = 'unpaid';
console.log("Is car == 'unpaid'? I predict True.");
console.log(fees3 == 'paid');